"""change start_time type(remove)

Revision ID: 9355bacf1284
Revises: 2b34a31c757f
Create Date: 2020-12-22 03:12:45.220417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9355bacf1284'
down_revision = '2b34a31c757f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
