"""alter field length

Revision ID: c96301e72add
Revises: e9864fea85cd
Create Date: 2020-12-22 15:55:50.391490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96301e72add'
down_revision = 'e9864fea85cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
